package(
  default_visibility = ['//:__pkg__'],
)

load('@rules_foreign_cc//foreign_cc:defs.bzl', 'configure_make')

filegroup(
  name = 'all_srcs',
  srcs = glob(['**'], exclude = ['bazel-*/**']),
)

cc_library(
  name = "system_libibverbs",
  linkopts = ["-libverbs"],
)

cc_library(
  name = "system_librdmacm",
  linkopts = ["-lrdmacm"],
)

CONFIGURE_OPTIONS = [
  '--disable-tests',
  '--disable-unit-tests',
  '--disable-examples',
  '--without-nvme-cuse',
  '--with-crypto',
  '--with-rdma',
  '--with-openssl=$$EXT_BUILD_DEPS/openssl',
  '--without-shared',
]

configure_make(
  name = 'spdk',
  lib_source = ':all_srcs',
  configure_options = CONFIGURE_OPTIONS,
  alwayslink = True,
  out_lib_dir = 'lib',
  out_static_libs = [
    "libspdk_accel.a",
    "libspdk_accel_dpdk_cryptodev.a",
    "libspdk_accel_error.a",
    "libspdk_accel_ioat.a",
    "libspdk_bdev.a",
    "libspdk_bdev_aio.a",
    "libspdk_bdev_crypto.a",
    "libspdk_bdev_delay.a",
    "libspdk_bdev_error.a",
    "libspdk_bdev_ftl.a",
    "libspdk_bdev_gpt.a",
    "libspdk_bdev_lvol.a",
    "libspdk_bdev_malloc.a",
    "libspdk_bdev_null.a",
    "libspdk_bdev_nvme.a",
    "libspdk_bdev_passthru.a",
    "libspdk_bdev_raid.a",
    "libspdk_bdev_split.a",
    "libspdk_bdev_virtio.a",
    "libspdk_bdev_zone_block.a",
    "libspdk_blob.a",
    "libspdk_blob_bdev.a",
    "libspdk_blobfs.a",
    "libspdk_blobfs_bdev.a",
    "libspdk_conf.a",
    "libspdk_dma.a",
    "libspdk_env_dpdk.a",
    "libspdk_env_dpdk_rpc.a",
    "libspdk_event.a",
    "libspdk_event_accel.a",
    "libspdk_event_bdev.a",
    "libspdk_event_fsdev.a",
    "libspdk_event_iobuf.a",
    "libspdk_event_iscsi.a",
    "libspdk_event_keyring.a",
    "libspdk_event_nbd.a",
    "libspdk_event_nvmf.a",
    "libspdk_event_scheduler.a",
    "libspdk_event_scsi.a",
    "libspdk_event_sock.a",
    "libspdk_event_vhost_blk.a",
    "libspdk_event_vhost_scsi.a",
    "libspdk_event_vmd.a",
    "libspdk_fsdev.a",
    "libspdk_fsdev_aio.a",
    "libspdk_ftl.a",
    "libspdk_fuse_dispatcher.a",
    "libspdk_init.a",
    "libspdk_ioat.a",
    "libspdk_iscsi.a",
    "libspdk_json.a",
    "libspdk_jsonrpc.a",
    "libspdk_keyring.a",
    "libspdk_keyring_file.a",
    "libspdk_keyring_linux.a",
    "libspdk_log.a",
    "libspdk_lvol.a",
    "libspdk_nbd.a",
    "libspdk_notify.a",
    "libspdk_nvme.a",
    "libspdk_nvmf.a",
    "libspdk_rdma_provider.a",
    "libspdk_rdma_utils.a",
    "libspdk_rpc.a",
    "libspdk_scheduler_dpdk_governor.a",
    "libspdk_scheduler_dynamic.a",
    "libspdk_scheduler_gscheduler.a",
    "libspdk_scsi.a",
    "libspdk_sock.a",
    "libspdk_sock_posix.a",
    "libspdk_thread.a",
    "libspdk_trace.a",
    "libspdk_trace_parser.a",
    "libspdk_ut_mock.a",
    "libspdk_util.a",
    "libspdk_vfio_user.a",
    "libspdk_vhost.a",
    "libspdk_virtio.a",
    "libspdk_vmd.a",
    "librte_bus_auxiliary.a",
    "librte_bus_pci.a",
    "librte_bus_vdev.a",
    "librte_cmdline.a",
    "librte_common_mlx5.a",
    "librte_common_qat.a",
    "librte_compressdev.a",
    "librte_crypto_ipsec_mb.a",
    "librte_crypto_mlx5.a",
    "librte_cryptodev.a",
    "librte_dmadev.a",
    "librte_eal.a",
    "librte_ethdev.a",
    "librte_hash.a",
    "librte_kvargs.a",
    "librte_log.a",
    "librte_mbuf.a",
    "librte_mempool.a",
    "librte_mempool_ring.a",
    "librte_meter.a",
    "librte_net.a",
    "librte_pci.a",
    "librte_power.a",
    "librte_power_acpi.a",
    "librte_power_amd_pstate.a",
    "librte_power_cppc.a",
    "librte_power_intel_pstate.a",
    "librte_power_intel_uncore.a",
    "librte_power_kvm_vm.a",
    "librte_rcu.a",
    "librte_reorder.a",
    "librte_ring.a",
    "librte_security.a",
    "librte_telemetry.a",
    "librte_timer.a",
    "librte_vhost.a",
    "libisal.a",
    "libisal_crypto.a",
  ],
  configure_in_place = True,
  env = {
    'PKG_CONFIG_PATH': '/usr/lib/x86_64-linux-gnu/pkgconfig',
  },
  deps = [
    '@openssl',
    '@zlib',
    ':system_libibverbs',
    ':system_librdmacm',
  ],
  linkopts = ['-lz'],
  visibility = ['//visibility:public'],
)
